daysUntilStale: 90
daysUntilClose: 90

exemptLabels:
- type/bug
- type/cleanup
- type/feature
- type/infrastructure
- critical
- security
exemptMilestones: true
exemptAssignees: true

staleLabel: wontfix

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
